[package]
name = "gaffs"
version = "0.1.0"
authors = ["Jon Doe <agustusfifth@gmail.com>"]

[dependencies]
failure = "*"
failure_derive = "*"
toml = "*"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
